[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"

[rpc_endpoints]
fuji = "https://api.avax-test.network/ext/bc/C/rpc"
fuji_backup = "https://avalanche-fuji-c-chain-rpc.publicnode.com"

[etherscan]
fuji = { key = "${SNOWTRACE_API_KEY}", url = "https://api-testnet.snowtrace.io/api" }

